-- 8 JUNE 2026
-- World Wide Energy Consumption Analysis

CREATE DATABASE  ENERGYDB;
USE ENERGYDB;
DROP DATABASE ENERGYDB;

-- 1. country table
CREATE TABLE country (
	Country VARCHAR(100) UNIQUE,
    CID VARCHAR(10) PRIMARY KEY
);
DROP TABLE country;
SELECT * FROM COUNTRY;
DESC COUNTRY;
ALTER TABLE COUNTRY
MODIFY COUNTRY VARCHAR(100) UNIQUE,
MODIFY CID VARCHAR(10) PRIMARY KEY;

-- 2. emission_3 table
CREATE TABLE emissions (
    country VARCHAR(100),
    energy_type VARCHAR(50),
    year INT,
    emission INT,
    per_capita_emission DOUBLE,
    FOREIGN KEY (country) REFERENCES country(Country)
);

ALTER TABLE EMISSIONS
MODIFY EMISSION DOUBLE;

SELECT * FROM EMISSIONS;

DROP TABLE IF EXISTS emissions;

-- 3. population table
CREATE TABLE population (
    countries VARCHAR(100),
    year INT,
    Value DOUBLE,
    FOREIGN KEY (countries) REFERENCES country(Country)
);


-- 4. production table
CREATE TABLE production (
    country VARCHAR(100),
    energy VARCHAR(50),
    year INT,
    production INT,
    FOREIGN KEY (country) REFERENCES country(Country)
);
ALTER TABLE production
MODIFY production DOUBLE;


-- 5. gdp_3 table
CREATE TABLE gdp_3 (
    Country VARCHAR(100),
    year INT,
    Value DOUBLE,
    FOREIGN KEY (Country) REFERENCES country(Country)
);

ALTER TABLE gdp_3
RENAME TO GDP;

-- 6. consumption table
CREATE TABLE consumption (
    country VARCHAR(100),
    energy VARCHAR(50),
    year INT,
    consumption INT,
    FOREIGN KEY (country) REFERENCES country(Country)
);

ALTER TABLE consumption
MODIFY consumption DECIMAL(10,7);

DESC consumption;
DROP TABLE CONSUMPTION;
TRUNCATE TABLE CONSUMPTION;

SHOW TABLES; -- 6 TABLES

SELECT * FROM CONSUMPTION
WHERE COUNTRY = 'British Virgin Islands' AND 
YEAR = 2022
ORDER BY YEAR DESC;

SELECT DISTINCT(CONSUMPTION) FROM CONSUMPTION;
SELECT * FROM COUNTRY;
SELECT * FROM EMISSIONS;
SELECT DISTINCT(emission) FROM EMISSIONS;

-- ------------------------------------------------------
#Data Analysis Questions
-- -------------------------------------------------------
/*General & Comparative Analysis*/
/*1. What is the total emission per 
country for the most recent year available?*/
SELECT COUNTRY,MAX(YEAR) AS RECENT_YEAR, SUM(EMISSION) AS TOTAL_EMISSION
FROM EMISSIONS
GROUP BY COUNTRY
ORDER BY  RECENT_YEAR DESC,TOTAL_EMISSION DESC;
/*China	with 92338.18520520002
United States with 38453.994441999996
India	with 20221.3305495 tonnes of CO2 of total emission for the year 2023.*/

/*2. What are the top 5 countries 
by GDP in the most recent year?*/
SELECT COUNTRY, VALUE, 
	   YEAR AS RECENT_YEAR
FROM GDP
WHERE YEAR = 
	(SELECT MAX(YEAR) FROM GDP) 
ORDER BY VALUE DESC
LIMIT 5;
/*China	28673.24	2024
United States	22679.47	2024
India	11660.21	2024
Japan	5179.704	2024
Germany	4463.949	2024*/


/*3. Compare energy production and 
consumption by country and year. */
SELECT COUNT(P.COUNTRY) OVER(),P.COUNTRY, P.YEAR
FROM PRODUCTION P
JOIN CONSUMPTION C
ON P.COUNTRY = C.COUNTRY
GROUP BY P.COUNTRY, P.YEAR;

SELECT COUNT(DISTINCT P.COUNTRY) 
FROM PRODUCTION P
JOIN CONSUMPTION C
ON P.COUNTRY = C.COUNTRY;

SELECT * FROM COUNTRY;
##################################### WHAT ABOUT TOP CONSUMPTION PER YEAR?
#ANSWER
SELECT P.COUNTRY, P.YEAR, 
SUM(PRODUCTION) AS TOTAL_PRODUCTION,
SUM(CONSUMPTION) AS TOTAL_CONSUMPTION,
SUM(PRODUCTION) - SUM(CONSUMPTION) AS MARGIN
FROM PRODUCTION P
JOIN CONSUMPTION C
ON P.COUNTRY = C.COUNTRY
GROUP BY P.COUNTRY, P.YEAR
ORDER BY YEAR DESC,TOTAL_PRODUCTION DESC;


/* 4. Which energy types contribute 
most to emissions across all countries?*/

#ANSWER
SELECT ENERGY_TYPE, SUM(EMISSION)  AS TOTAL_EMISSION
FROM EMISSIONS
GROUP BY ENERGY_TYPE
ORDER BY TOTAL_EMISSION DESC;
/*CO2 emissions*/
############################## each in how many countries?
/*CO2 emissions (MMtonnes CO2)	142731.60422988687	
Coal and coke (MMtonnes CO2)	63959.18749735431	*/

/* 5. Trend Analysis Over Time
How have global emissions changed year over year?*/
SELECT * FROM EMISSIONS;

SELECT YEAR,
SUM(EMISSION) AS TOTAL_EMISSION,
coalesce(coalesce(SUM(EMISSION),0) 
			- LAG(coalesce(SUM(EMISSION),0)) OVER()
		,0) 
    AS DIFF,
CONCAT(coalesce( #coalesce is to turn null to 0
			round(
			(coalesce(coalesce(SUM(EMISSION),0) - 
				LAG(coalesce(SUM(EMISSION),0)) OVER(),0))*100/
				(LAG(coalesce(SUM(EMISSION),0)) OVER())
			,3) -- round to 3 decimals
		,0) 
	,"%") -- concat % symbol to number
AS DIFF_PERCENTAGE
FROM EMISSIONS 
GROUP BY YEAR 
ORDER BY TOTAL_EMISSION;
/*
2020	67855.22185297697	0	                0%
2021	70991.42816796797	3136.2063149909955	4.622%
2022	72458.19597191211	1466.767803944138	2.066%
2023	74158.36247248718	1700.1665005750692	2.346%*/

/*What is the trend in GDP for each country over the given years?*/
SELECT COUNTRY, YEAR, VALUE,
round(coalesce((VALUE - LAG(VALUE) OVER())
	  ,0)
,3) AS DIFFERENCE
FROM GDP
WHERE (YEAR IN (SELECT DISTINCT(YEAR) FROM GDP))
-- WHERE (YEAR IN (SELECT DISTINCT(YEAR) FROM GDP)) AND COUNTRY = 'INDIA' -- FOR INDIA
ORDER BY COUNTRY, YEAR;

SELECT DISTINCT(YEAR) FROM GDP;

SELECT COUNTRY, YEAR, VALUE 
FROM GDP
WHERE (YEAR IN (SELECT DISTINCT(YEAR) FROM GDP)) AND COUNTRY = 'INDIA'
ORDER BY COUNTRY;

/*How has population growth affected total emissions in each country?*/

/*GROWTH AFFECT FOR TOP 5 COUNTRIES BY GDP*/
WITH POPULATION AS 
(SELECT countries, year, SUM(Value) TOT_POPULATION
FROM POPULATION
GROUP BY countries, year
ORDER BY COUNTRIES),
EMISSION AS (SELECT country, year, 
SUM(EMISSION) TOT_EMISSION
FROM EMISSIONS
GROUP BY country, year
ORDER BY COUNTRY)

SELECT P.COUNTRIES, E.YEAR,  P.TOT_POPULATION, E.TOT_EMISSION,
coalesce(P.TOT_POPULATION - LAG(P.TOT_POPULATION) OVER(PARTITION BY P.COUNTRIES),0),
coalesce(E.TOT_EMISSION - LAG(E.TOT_EMISSION) OVER(PARTITION BY P.COUNTRIES),0)
FROM POPULATION P 
JOIN EMISSION E
ON P.COUNTRIES = E.COUNTRY
WHERE P.COUNTRIES IN 
	(SELECT G.COUNTRY 
		FROM 
			(SELECT COUNTRY, SUM(VALUE) 
				FROM GDP 
				GROUP BY COUNTRY
                ORDER BY SUM(VALUE) DESC
			LIMIT 5) 
	G) 
AND
P.YEAR = E.YEAR;

SELECT G.COUNTRY FROM (SELECT COUNTRY, SUM(VALUE) FROM GDP 
GROUP BY COUNTRY
ORDER BY SUM(VALUE) DESC
LIMIT 5) G; 
/*ANSWER*/
WITH POPULATION AS 
(SELECT countries, year, SUM(Value) TOT_POPULATION
FROM POPULATION
GROUP BY countries, year
ORDER BY COUNTRIES),
EMISSION AS (SELECT country, year, 
SUM(EMISSION) TOT_EMISSION
FROM EMISSIONS
GROUP BY country, year
ORDER BY COUNTRY)

-- SELECT P.COUNTRIES, E.YEAR, E.TOT_EMISSION, P.TOT_POPULATION 
SELECT P.COUNTRIES, E.YEAR,  P.TOT_POPULATION, E.TOT_EMISSION
FROM POPULATION P 
JOIN EMISSION E
ON P.COUNTRIES = E.COUNTRY
WHERE P.YEAR = E.YEAR; -- 0.016 Sec duration to fetch
-- Afghanistan	2023	41454.76
-- ORDER BY P.YEAR,E.YEAR,
-- P.TOT_POPULATION DESC, E.TOT_EMISSION;
#SELECT * FROM POPULATION; -- countries, year, TOT_POPULATION
#SELECT * FROM EMISSION; -- country, year, TOT_EMISSION

SELECT 
P.countries, P.year, P.Value, E.EMISSION
FROM POPULATION P
JOIN EMISSIONS E
ON P.COUNTRIES = E.COUNTRY
WHERE P.YEAR = E.YEAR
ORDER BY E.YEAR, P.YEAR;

SELECT COUNTRIES, YEAR, P.VALUE
FROM POPULATION P
WHERE YEAR = 2023
ORDER BY P.YEAR DESC; -- 42647.49 2024
SELECT YEAR,COUNTRY, SUM(E.EMISSION) FROM EMISSIONS E
WHERE YEAR  = 2023
GROUP BY YEAR,COUNTRY
ORDER BY COUNTRY;

DESC EMISSIONS;

-- Afghanistan	2020	18.732471972	Afghanistan	2024	42647.49
-- Afghanistan	2020	18.732471972	42647.49

# 10 JUNE 2026
/*Has energy consumption increased or decreased over the years for major economies?*/

SELECT CS.COUNTRY, 
		CS.YEAR,
        SUM(CS.CONSUMPTION) AS CONSUMPTION_BY_YEAR ,
        coalesce(SUM(CS.CONSUMPTION) - LAG(SUM(CS.CONSUMPTION)) OVER(partition by COUNTRY),0)   AS GROWTH
        FROM CONSUMPTION CS
WHERE CS.COUNTRY IN 
		(SELECT C.COUNTRY 
			FROM 
				(SELECT G.Country,  SUM(G.Value) 
                FROM GDP G
				GROUP BY G.Country
				ORDER BY  SUM(G.Value)  DESC
				LIMIT 5) 
		C)
GROUP BY CS.COUNTRY, CS.YEAR; 
# ONLY FOR COUNTRIES INDIA AND CHINA CONSUMPTION SEEM TO INCREASE YEAR BY YEAR
# FOR REST OF TOP 3 COUNTRIES CONSUMPTION HAS BEEN FLUCTUATING AND GOING 
# DOWN TREND MEANING THEIR CONSUMPTION AND THUS EMISSION FROM PREVIOUS QUERY WE CAN FIND
# HAS BEEN DECREASING.

/*What is the average yearly change 
in emissions per capita for each country?*/
SELECT PC.country,  AVG(PC.YEARLY_CHANGE) AS AVG_YEARLY_CHANGE
FROM 
	(SELECT country,  year,  
		SUM(per_capita_emission) AS Per_capita_Per_year,
        coalesce(SUM(per_capita_emission) - LAG(SUM(per_capita_emission)) OVER(PARTITION BY YEAR),0) AS YEARLY_CHANGE
		FROM EMISSIONS
        GROUP BY country,  year,  
		per_capita_emission
		ORDER BY COUNTRY
	) PC
GROUP BY PC.country
HAVING AVG(PC.YEARLY_CHANGE) != 0
ORDER BY AVG(PC.YEARLY_CHANGE) DESC;

/*Afghanistan	2020	0.028504384
Afghanistan	2021	0.021378288000000002
Afghanistan	2022	0.021378288000000002
Afghanistan	2023	0.021378288000000002*/


/*Ratio & Per Capita Analysis*/
/*What is the emission-to-GDP ratio for each country by year?*/
SELECT G.COUNTRY,G.YEAR, SUM(E.EMISSION) AS TOTAL_EMISSION, G.VALUE GDP_OF_YEAR ,
					SUM(E.EMISSION)/ G.VALUE AS EMISSION_TO_GDP_RATIO
FROM EMISSIONS E
JOIN GDP G
WHERE G.COUNTRY = E.COUNTRY AND G.YEAR = E.YEAR 
GROUP BY G.COUNTRY,G.YEAR, G.VALUE
ORDER BY YEAR DESC, EMISSION_TO_GDP_RATIO DESC;
/*10937.52
10047.18
9387.808
8572.151*/
SELECT G.COUNTRY,G.YEAR, G.VALUE GDP_OF_YEAR FROM GDP G
WHERE G.COUNTRY = 'INDIA';


/*What is the energy consumption per capita for each country over the last decade?*/
WITH MAX_YEAR AS (SELECT COUNTRY, SUM(per_capita_emission), YEAR AS DECADE 
FROM EMISSIONS
GROUP BY COUNTRY, YEAR),
MIN_YEAR AS (SELECT COUNTRY, SUM(per_capita_emission)
FROM EMISSIONS
WHERE YEAR = (SELECT MAX(YEAR) - 10 FROM EMISSIONS)
GROUP BY COUNTRY)
SELECT * FROM MAX_YEAR;

/*How does energy production per capita vary across countries?
*/
SELECT PR.COUNTRY, ROUND(SUM(PR.PRODUCTION),10) AS Total_Production,
		ROUND(SUM(PR.PRODUCTION)/SUM(P.VALUE),10) PER_CAPITA,
        variance(SUM(PR.PRODUCTION)/SUM(P.VALUE)) OVER() VARIANCE_ACROSS,
        AVG(SUM(PR.PRODUCTION)/SUM(P.VALUE)) OVER() AVG_PER_CAPITA_ACROSS
 FROM PRODUCTION PR
 JOIN POPULATION P 
 ON PR.COUNTRY = P.COUNTRIES
 GROUP BY PR.COUNTRY
 ORDER BY PER_CAPITA DESC;
 
/*Which countries have the 
highest energy consumption relative to GDP?*/
SELECT C.COUNTRY, SUM(C.CONSUMPTION) ENGCN, SUM(C.CONSUMPTION)/SUM(G.VALUE) REL
FROM CONSUMPTION C 
JOIN GDP G 
WHERE C.COUNTRY = G.COUNTRY
GROUP BY C.COUNTRY
ORDER BY ENGCN DESC, REL DESC ;


/*What is the correlation between GDP growth and energy production growth?*/
SELECT 
    (AVG(x * y) - AVG(x) * AVG(y)) / 
    (SQRT(AVG(x * x) - AVG(x) * AVG(x)) * SQRT(AVG(y * y) - AVG(y) * AVG(y))) 
    AS pearson_correlation
FROM GDP G
JOIN PRODUCTION P;
/*coor = */


/* Global Comparisons*/

/*What are the top 10 countries by 
population and how do their emissions compare?*/
SELECT P.COUNTRIES, SUM(P.VALUE) AS TOT_POPULATION,
SUM(E.EMISSION) AS TOT_EMISSION
FROM POPULATION P
JOIN EMISSIONS E 
WHERE P.COUNTRIES = E.COUNTRY
GROUP BY P.COUNTRIES, E.COUNTRY
ORDER BY TOT_POPULATION DESC
LIMIT 10;

/*Which countries have improved (reduced) 
their per capita emissions the most over the last decade?*/


/*What is the global share (%) of emissions by country?*/
SELECT COUNTRY, SUM(EMISSION) AS TOT_EMISSION,
        EMISSION_COUNTRY FROM (
			SELECT SUM(EMISSION) OVER(PARTITION BY COUNTRY) AS EMISSION_COUNTRY
            FROM EMISSIONS),
        -- 
        -- ((SUM(EMISSION) OVER(PARTITION BY COUNTRY))*100/SUM(EMISSION)) AS GLOBAL_SHARE
        FROM EMISSIONS
        GROUP BY COUNTRY;

/*What is the global average GDP, emission, and population by year?
*/
WITH T1 AS (SELECT YEAR, AVG(G.VALUE) AVG_GDP FROM GDP G
GROUP BY YEAR
ORDER BY AVG_GDP),
T2 AS (SELECT E.YEAR,AVG(E.EMISSION) AVG_EMIS FROM EMISSIONS E
GROUP BY E.YEAR
ORDER BY AVG_EMIS), 
T3 AS (SELECT P.YEAR,AVG(P.VALUE) AVG_POPULATION FROM POPULATION P
GROUP BY P.YEAR
ORDER BY AVG_POPULATION)
SELECT T1.YEAR, T1.AVG_GDP, T2.AVG_EMIS, T3.AVG_POPULATION
	FROM T1
    JOIN T2
    ON T1.YEAR = T2.YEAR
    JOIN T3
    ON T1.YEAR = T3.YEAR;